### ISSUE TITLE
Set mode when installing file content

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/docker-setup#2705]
- [x] Add option to set mode for files:

  ```yaml
  tools:
  - name: foo
    #...
    files:
    - path: bar
      mode: 0755
      content: baz
  ```

- [x] Add option to set mode for downloads:

  ```yaml
  tools:
  - name: bar
    #...
    download:
    - url: ...
      type: file
      path: ...
      mode: 0755
  ```

- [x] Add mode to files as well as download and remove `chmod` from `post_install`
