### ISSUE TITLE
Install alternative runtimes

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/docker-setup#59]
- [ ] kata-containers (https://github.com/kata-containers/kata-containers/releases/download/2.4.3/kata-static-2.4.3-x86_64.tar.xz)

  ```yaml
  - name: kata-containers
    hidden: true
    version: 2.4.3
    binary: kata-runtime
    check: ${binary} --version | head -n 1 | tr -d ' ' | cut -d':' -f2
    needs:
    - docker
    - qemu
    tags:
    - runtime
    download:
    - url: https://github.com/kata-containers/kata-containers/releases/download/2.4.3/kata-static-2.4.3-x86_64.tar.xz
      type: tarball-xz
      path: ${target}
      strip: 3
  ```

- [x] gvisor
- [ ] sysbox (https://github.com/nestybox/sysbox/blob/master/docs/developers-guide/build.md)
